// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteEF;

namespace TesteEF.Migrations
{
    [DbContext(typeof(TesteEFDBContext))]
    partial class TesteEFDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaosAObra02.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BLOG")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTimeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CREATED");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_USER_BLOG");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("DSC_BLOG");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("TB_BLOG");
                });

            modelBuilder.Entity("MaosAObra02.Models.Pedido", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PEDIDO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Compra")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_COMPRA");

                    b.Property<string>("Descricao_Pedido")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("DESCRICAO_PEDIDO");

                    b.Property<int>("Id_Produto_Pedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO_PEDIDO");

                    b.Property<decimal>("Valor_Pedido")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_PEDIDO");

                    b.HasKey("Id_Pedido");

                    b.HasIndex("Id_Produto_Pedido");

                    b.ToTable("TB_PEDIDO");
                });

            modelBuilder.Entity("MaosAObra02.Models.Produto", b =>
                {
                    b.Property<int>("Id_Produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Validade")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VALIDADE");

                    b.Property<string>("Nome_Produto")
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("NOME_PRODUTO");

                    b.Property<decimal>("Preco_Produto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRECO_PRODUTO");

                    b.Property<string>("Tipo_Produto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_PRODUTO");

                    b.HasKey("Id_Produto");

                    b.ToTable("TB_PRODUTO");
                });

            modelBuilder.Entity("MaosAObra02.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USER")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameUser")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("DSC_USER");

                    b.HasKey("Id");

                    b.ToTable("TB_USER");
                });

            modelBuilder.Entity("MaosAObra02.Models.Blog", b =>
                {
                    b.HasOne("MaosAObra02.Models.User", "User")
                        .WithMany("Blog")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaosAObra02.Models.Pedido", b =>
                {
                    b.HasOne("MaosAObra02.Models.Produto", "Produto")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_Produto_Pedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MaosAObra02.Models.Produto", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MaosAObra02.Models.User", b =>
                {
                    b.Navigation("Blog");
                });
#pragma warning restore 612, 618
        }
    }
}
