// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjMercado.Data;

namespace ProjMercado.Migrations
{
    [DbContext(typeof(ProjMercadoContext))]
    [Migration("20210924210359_DataTypeUsuario")]
    partial class DataTypeUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjMercado.Models.Produto", b =>
                {
                    b.Property<int>("Id_Produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Validade")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VALIDADE");

                    b.Property<string>("Nome_Produto")
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("NOME_PRODUTO");

                    b.Property<decimal>("Preco_Produto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECO_PRODUTO");

                    b.Property<string>("Tipo_Produto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_PRODUTO");

                    b.HasKey("Id_Produto");

                    b.ToTable("TB_PRODUTO");
                });

            modelBuilder.Entity("ProjMercado.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome_Usuario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO");
                });

            modelBuilder.Entity("ProjMercado.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal>("Valor_Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("TB_VENDA");
                });

            modelBuilder.Entity("ProjMercado.Models.VendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA_ITEM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Produto")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("Id_Venda")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("Id_Produto");

                    b.HasIndex("Id_Venda");

                    b.ToTable("TB_VENDA_ITEM");
                });

            modelBuilder.Entity("ProjMercado.Models.Venda", b =>
                {
                    b.HasOne("ProjMercado.Models.Usuario", "Usuario")
                        .WithMany("Vendas")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjMercado.Models.VendaItem", b =>
                {
                    b.HasOne("ProjMercado.Models.Produto", "Produto")
                        .WithMany("ItensDoProdutoVendido")
                        .HasForeignKey("Id_Produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjMercado.Models.Venda", "Venda")
                        .WithMany("Items")
                        .HasForeignKey("Id_Venda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ProjMercado.Models.Produto", b =>
                {
                    b.Navigation("ItensDoProdutoVendido");
                });

            modelBuilder.Entity("ProjMercado.Models.Usuario", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ProjMercado.Models.Venda", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
